
[GaussianProcesses.GPClassifier]
":package_uuid" = "891a1506-143c-57d2-908e-e1f8e92e6de9"
":load_path" = "MLJModels.GaussianProcesses_.GPClassifier"
":input_quantity" = ":multivariate"
":is_pure_julia" = ":yes"
":package_url" = "https://github.com/STOR-i/GaussianProcesses.jl"
":package_name" = "GaussianProcesses"
":output_is_probabilistic" = ":no"
":name" = "GPClassifier"
":output_kind" = ":ordered_factor_finite"
":output_quantity" = ":univariate"
":input_kinds" = [":continuous"]
":learning_type" = ":supervised"

[DecisionTree.DecisionTreeClassifier]
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeClassifier"
":input_quantity" = ":multivariate"
":is_pure_julia" = ":yes"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_name" = "DecisionTree"
":output_is_probabilistic" = ":yes"
":name" = "DecisionTreeClassifier"
":output_kind" = ":multiclass"
":output_quantity" = ":univariate"
":input_kinds" = [":continuous"]
":learning_type" = ":supervised"

[Clustering.KMeans]
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMeans"
":input_quantity" = ":multivariate"
":is_pure_julia" = ":yes"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":output_is_probabilistic" = ":unknown"
":name" = "KMeans"
":output_kind" = ":continuous"
":output_quantity" = ":multivariate"
":input_kinds" = [":continuous"]
":learning_type" = ":unsupervised"

[Clustering.KMedoids]
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":load_path" = "MLJModels.Clustering_.KMedoids"
":input_quantity" = ":multivariate"
":is_pure_julia" = ":yes"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":output_is_probabilistic" = ":unknown"
":name" = "KMedoids"
":output_kind" = ":continuous"
":output_quantity" = ":multivariate"
":input_kinds" = [":continuous"]
":learning_type" = ":unsupervised"

[GLM.OLSRegressor]
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.OLSRegressor"
":input_quantity" = ":multivariate"
":is_pure_julia" = ":yes"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":output_is_probabilistic" = ":no"
":name" = "OLSRegressor"
":output_kind" = ":continuous"
":output_quantity" = ":univariate"
":input_kinds" = [":continuous"]
":learning_type" = ":supervised"
