GaussianProcesses = ["GPClassifier"]
DecisionTree = ["DecisionTreeClassifier"]
ScikitLearn = ["SVMRegressor", "SVMNuClassifier", "SVMClassifier", "SVMLRegressor", "SVMNuRegressor", "SVMLClassifier"]
Clustering = ["KMeans", "KMedoids"]
GLM = ["OLSRegressor", "GLMCountRegressor"]
NaiveBayes = ["GaussianNBClassifier", "MultinomialNBClassifier"]
