name = "MLJRegistry"
uuid = "a41df0fa-2d8a-11e9-1bfb-8110be68cd3e"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.0"

[deps]
TOML = "191fdcea-f9f2-43e0-b922-d33f71e2abc3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
